### PR TITLE
Add wpiutil dependency to commandv1

### PR DESCRIPTION
**Pull request by TheTripleV**

### CODE REVIEW

**Review by auscompgeek — APPROVED** [review]

**Comment by virtuald** [comment]
robotpy-wpilib should bring in wpiutil?

**Comment by auscompgeek** [comment]
This needs to link directly to wpiutil though.

**Comment by virtuald** [comment]
Does it? Hm, maybe that's the symbol problem @TheTripleV ran into then?

**Comment by auscompgeek** [comment]
Yeah. Since commands use wpiutil directly, it's a direct dependency so needs to be linked to.

**Pull request merged**
